API_KEY: pHEiDorWAd10tojmlKa48GPa
SECRET_KEY: 5EkzljmuQ3pZ5u0KaWzT3szdgb9Gs0b9

# 发音人选择, 基础音库：0为度小美，1为度小宇，3为度逍遥，4为度丫丫，
PER: 1

# 语速，取值0-15，默认为5中语速
SPD: 5

# 音调，取值0-15，默认为5中语调
PIT: 5

# 音量，取值0-9，默认为5中音量
VOL: 5
