version: XTARK-Mecanum

#Serial port param
port_name: /dev/ttyAMA0 #设备端口
baud_rate: 115200       #通信波特率，固定115200

#odom_frame: odom_raw       #里程计坐标系
base_frame: robot1/base_footprint  #底盘坐标系
#publish_odom_transform: False #是否发布odom->base_footprint坐标变换

is_omni: True             #是否为全向运动底盘

encoder_resolution: 1440  #编码器分辨率
wheel_diameter: 0.097     #轮胎直径
wheel_track: 0.17         #麦轮A参数+麦轮B参数
linear_correction_factor: 1.000    #线速度校准系数
angular_correction_factor: 1.000  #角速度校准系数
robot_linear_acc: 2.5     #线加速度m/s2
robot_angular_acc: 5.0    #角加速度m/s2


#Motor PID params
Kp: 300                 #OpenCRP电机控制PID，P参数
Ki: 0                   #OpenCRP电机控制PID，I参数
Kd: 200                 #OpenCRP电机控制PID, D参数

#Other
control_rate: 25        #底盘控制频率
